### PR TITLE
Adds JWT token support

### PR DESCRIPTION
**Pull request by hkernbach**
This PR adds JWT token support. It does not maintain the JWT itself but grants an alternative to the basic authentication (with username and password). Therefore I've introduces one API change which changes the optional `auth?` flag to
`auth_mode` which accepts `Arangox.Auth.t()` as an option. 

Valid options are (auth.ex): 
```
  @type t ::
          :off
          | {:basic, username, password}
          | {:jwt, bearer}
```

In short:
* Pulled username and password out of the main struct (Connection) into the `auth_mode` map itself, as username and password now are only required in case `auth` is set to `:basic`

Additional:
* Moves doctest into its own file as the old structure did not automatically re-compile the `Readme.md`. Therefore it was hard to detect and change code there. (Basically before, the whole compilation folder under `_build` had to be manually removed because detection changes in `Readme.md` where not possible). 

Tests do work now and are fully green. A review would be appreciated :)

### CODE REVIEW

**Comment by hkernbach** [comment]
Tests:
```
 arangox via  feature/PREG-327  via  desktop-linux via  v1.15.7 (OTP 25)
➜ mix test
........................................................................
Finished in 6.7 seconds (6.7s async, 0.00s sync)
11 doctests, 61 tests, 0 failures

Randomized with seed 39660
```

**Comment by hkernbach** [comment]
@suazithustra I've send you an e-mail to your gmail address I've found in the changelog with some questions related to arangox. Is that mail still active? Just asking as I'm just not sure if it reached you or not 😄

**Comment by suazithustra** [comment]
> @suazithustra I've send you an e-mail to your gmail address I've found in the changelog with some questions related to arangox. Is that mail still active? Just asking as I'm just not sure if it reached you or not 😄

Don't you wish Github had some chat/messaging features? 🤷

I'm reading the email, I'll reply shortly.

**Review by suazithustra — CHANGES_REQUESTED** [review]
Hey Heiko. Please forgive the delay.

There are a couple of things we can do before we merge.

We should make the default behavior consistent with the other drivers by removing the default basic authentication.

The API could be more idiomatic to Elixir and more consistent with the other drivers if we do the following:

* Don't use functions to generate atoms for configuration
* Rename `:auth_mode` to `:auth`
* remove the `authentication_` prefixes in `Arangox.Auth`
* rename `:jwt` to `:bearer`

**Comment by hkernbach** [comment]
> There are a couple of things we can do before we merge.
> 
> We should make the default behavior consistent with the other drivers by removing the default basic authentication.
> 
Changed here: https://github.com/ArangoDB-Community/arangox/pull/8/commits/52c88099e4a5ab15e2858c2cd31255837de4ac3c

> The API could be more idiomatic to Elixir and more consistent with the other drivers if we do the following:
> 
> * Don't use functions to generate atoms for configuration
> * Rename `:auth_mode` to `:auth`
> * remove the `authentication_` prefixes in `Arangox.Auth`
> * rename `:jwt` to `:bearer`

Modified here: https://github.com/ArangoDB-Community/arangox/pull/8/commits/1926cf964950a93a008a8ad6be183e4bba212a00

**Comment by suazithustra** [comment]
@hkernbach let me know as soon as you're finished

**Comment by hkernbach** [comment]
@suazithustra just fyi: As discussed, those changes now should be all hopefully final.

**Review by suazithustra — APPROVED** [review]

**Pull request merged**
