### PR TITLE
Update gun version

### PR DESCRIPTION
**Pull request by jvolmer**
In my project where I use arangox, I also want to be able to use the elixir package grpc, but this uses gun version 2.0 which is incompatible with the current gun version 1.3.3 in arangox.

Relevant change in gun 2 version (from gun/doc/src/guide/migrating_from_1.3.asciidoc):

> In order to get separate events when connecting, the domain lookup, connection and TLS handshakes are now performed separately by Gun. As a result, there exists three separate timeout options for each of the steps, and the transport options had to be split into tcp_opts and tls_opts.

### CODE REVIEW

**Comment by suazithustra** [comment]
Thanks for the PR.

I'm getting errors in the unit tests. Was this not the case for you?

```shell
arangox $ mix test test/arangox/client_test.exs
...........

  1) test velocy client: ssl and ssl_opts (Arangox.ClientTest)
     test/arangox/client_test.exs:98
     match (=) failed
     code:  assert {:ok, {:ssl, _port}} = VelocyClient.connect(@ssl, [])
     left:  {:ok, {:ssl, _port}}
     right: {:error, {:options, :incompatible, [verify: :verify_peer, cacerts: :undefined]}}
     stacktrace:
       test/arangox/client_test.exs:99: (test)

..........

  2) test gun client: ssl and ssl_opts (Arangox.ClientTest)
     test/arangox/client_test.exs:153
     match (=) failed
     code:  assert {:ok, _pid} = GunClient.connect(@ssl, [])
     left:  {:ok, _pid}
     right: {:error, {:down, {:shutdown, {:options, :incompatible, [verify: :verify_peer, cacerts: :undefined]}}}}
     stacktrace:
       test/arangox/client_test.exs:154: (test)


Finished in 2.3 seconds (2.3s async, 0.00s sync)
23 tests, 2 failures

Randomized with seed 337419
```

**Comment by jvolmer** [comment]
Right, these failures have nothing to do with this PR, they also occur in the main branch. Let me create another PR in the next days to fix this.

**Comment by suazithustra** [comment]
No need, it's working fine otherwise. I should have updated the tests, I'll take care of it.

Thanks again.

**Comment by suazithustra** [comment]
Published in [hex.pm](https://hex.pm/) as [v0.6.0](https://github.com/ArangoDB-Community/arangox/releases/tag/v0.6.0)

**Pull request merged**
